# -*- coding: utf-8 -*-
from django.db import models


class StatisticalDataReport(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    # A. PHÒNG HÀNH CHÍNH - QUẢN TRỊ
    # I. Bộ phận hướng dẫn + Tổng đài hỗ trợ 1900558826
    a_i_1_amount = models.IntegerField(default=0)
    a_i_1_note = models.CharField(blank=True, max_length=225)
    a_i_2_note = models.CharField(blank=True, max_length=255)
    a_i_2_1_amount = models.IntegerField(default=0)
    a_i_2_1_note = models.CharField(blank=True, max_length=225)
    a_i_2_2_amount = models.IntegerField(default=0)
    a_i_2_2_note = models.CharField(blank=True, max_length=225)
    a_i_2_3_amount = models.IntegerField(default=0)
    a_i_2_3_note = models.CharField(blank=True, max_length=225)
    a_i_2_4_amount = models.IntegerField(default=0)
    a_i_2_4_note = models.CharField(blank=True, max_length=225)
    a_i_3_amount = models.IntegerField(default=0)
    a_i_3_note = models.CharField(blank=True, max_length=225)
    a_i_4_amount = models.IntegerField(default=0)
    a_i_4_note = models.CharField(blank=True, max_length=225)
    # II.Bộ phận thu phí, lệ phí
    a_ii_1_amount = models.IntegerField(default=0)
    a_ii_1_note = models.CharField(blank=True, max_length=225)
    a_ii_2_note = models.CharField(blank=True, max_length=225)
    a_ii_2_1_amount = models.IntegerField(default=0)
    a_ii_2_1_note = models.CharField(blank=True, max_length=225)
    a_ii_2_2_amount = models.IntegerField(default=0)
    a_ii_2_2_note = models.CharField(blank=True, max_length=225)
    a_ii_2_3_amount = models.IntegerField(default=0)
    a_ii_2_3_note = models.CharField(blank=True, max_length=225)
    a_ii_2_4_amount = models.IntegerField(default=0)
    a_ii_2_4_note = models.CharField(blank=True, max_length=225)
    a_ii_2_5_amount = models.IntegerField(default=0)
    a_ii_2_5_note = models.CharField(blank=True, max_length=225)
    a_ii_3_amount = models.IntegerField(default=0)
    a_ii_3_note = models.CharField(blank=True, max_length=225)
    # III.Hoạt động của các bộ phận dịch vụ hỗ trợ
    a_iii_1_1_amount = models.IntegerField(default=0)
    a_iii_1_1_note = models.CharField(blank=True, max_length=225)
    a_iii_1_2_amount = models.IntegerField(default=0)
    a_iii_1_2_note = models.CharField(blank=True, max_length=225)
    a_iii_2_note = models.CharField(blank=True, max_length=225)
    a_iii_2_1_amount = models.IntegerField(default=0)
    a_iii_2_1_note = models.CharField(blank=True, max_length=225)
    a_iii_2_2_mount = models.IntegerField(default=0)
    a_iii_2_2_note = models.CharField(blank=True, max_length=225)
    a_iii_2_3_mount = models.IntegerField(default=0)
    a_iii_2_3_note = models.CharField(blank=True, max_length=225)
    a_iii_3_note = models.CharField(blank=True, max_length=225)
    a_iii_3_1_mount = models.IntegerField(default=0)
    a_iii_3_1_note = models.CharField(blank=True, max_length=225)
    a_iii_3_2_mount = models.IntegerField(default=0)
    a_iii_3_2_note = models.CharField(blank=True, max_length=225)
    a_iii_3_3_mount = models.IntegerField(default=0)
    a_iii_3_3_note = models.CharField(blank=True, max_length=225)
    a_iii_4_mount = models.IntegerField(default=0)
    a_iii_4_note = models.CharField(blank=True, max_length=225)
    a_iii_5_mount = models.IntegerField(default=0)
    a_iii_5_note = models.CharField(blank=True, max_length=225)
    a_iii_6_mount = models.IntegerField(default=0)
    a_iii_6_note = models.CharField(blank=True, max_length=225)
    a_iii_7_1_mount = models.IntegerField(default=0)
    a_iii_7_1_note = models.CharField(blank=True, max_length=225)
    a_iii_7_2_mount = models.IntegerField(default=0)
    a_iii_7_2_note = models.CharField(blank=True, max_length=225)
    # B. PHÒNG TIẾP NHẬN VÀ GIẢI QUYẾT TTHC
    # I. Tiếp nhận, giải quyết, trả kết quả TTHC tại Trung tâm Phục vụ hành chính công tỉnh
    # 1. Số hồ sơ mới được tiếp nhận trong ngày
    b_i_1_note = models.CharField(blank=True, max_length=225)
    b_i_1_1_amount = models.IntegerField(default=0)
    b_i_1_1_note = models.CharField(blank=True, max_length=225)
    b_i_1_2_amount = models.IntegerField(default=0)
    b_i_1_2_note = models.CharField(blank=True, max_length=225)
    b_i_1_3_amount = models.IntegerField(default=0)
    b_i_1_3_note = models.CharField(blank=True, max_length=225)
    # 2. Tổng số hồ sơ TTHC đã giải quyết trong ngày
    b_i_2_note = models.CharField(blank=True, max_length=225)
    b_i_2_1_amount = models.IntegerField(default=0)
    b_i_2_1_note = models.CharField(blank=True, max_length=225)
    b_i_2_2_amount = models.IntegerField(default=0)
    b_i_2_2_note = models.CharField(blank=True, max_length=225)
    b_i_2_3_amount = models.IntegerField(default=0)
    b_i_2_3_note = models.CharField(blank=True, max_length=225)
    # 3. Tổng số kết quả TTHC đã trả công dân trong ngày
    b_i_3_note = models.CharField(blank=True, max_length=225)
    b_i_3_1_amount = models.IntegerField(default=0)
    b_i_3_1_note = models.CharField(blank=True, max_length=225)
    b_i_3_2_amount = models.IntegerField(default=0)
    b_i_3_2_note = models.CharField(blank=True, max_length=225)
    b_i_3_3_amount = models.IntegerField(default=0)
    b_i_3_3_note = models.CharField(blank=True, max_length=225)
    # II. Các nội dung khác
    b_ii_1_1_amount = models.IntegerField(default=0)
    b_ii_1_1_note = models.CharField(blank=True, max_length=225)
    b_ii_1_2_amount = models.IntegerField(default=0)
    b_ii_1_2_note = models.CharField(blank=True, max_length=225)
    b_ii_2_1_amount = models.IntegerField(default=0)
    b_ii_2_1_note = models.CharField(blank=True, max_length=225)
    b_ii_2_2_amount = models.IntegerField(default=0)
    b_ii_2_2_note = models.CharField(blank=True, max_length=225)
    b_ii_3_amount = models.IntegerField(default=0)
    b_ii_3_note = models.CharField(blank=True, max_length=225)
    b_ii_4_amount = models.IntegerField(default=0)
    b_ii_4_note = models.CharField(blank=True, max_length=225)
    # C. PHÒNG KẾ HOẠCH TỔNG HỢP
    # I	Tiếp nhận, trả kết quả giải quyết TTHC tại các Trung tâm PVHCC cấp huyện
    c_i_1_1_amount = models.IntegerField(default=0)
    c_i_1_1_note = models.CharField(blank=True, max_length=225)
    c_i_1_2_amount = models.IntegerField(default=0)
    c_i_1_2_note = models.CharField(blank=True, max_length=225)
    c_i_2_note = models.CharField(blank=True, max_length=225)
    c_i_2_1_amount = models.IntegerField(default=0)
    c_i_2_1_note = models.CharField(blank=True, max_length=225)
    c_i_2_2_amount = models.IntegerField(default=0)
    c_i_2_2_note = models.CharField(blank=True, max_length=225)
    c_i_2_3_amount = models.IntegerField(default=0)
    c_i_2_3_note = models.CharField(blank=True, max_length=225)
    c_i_3_1_amount = models.IntegerField(default=0)
    c_i_3_1_note = models.CharField(blank=True, max_length=225)
    c_i_3_2_amount = models.IntegerField(default=0)
    c_i_3_2_note = models.CharField(blank=True, max_length=255)
    c_i_4_1_amount = models.IntegerField(default=0)
    c_i_4_1_note = models.CharField(blank=True, max_length=225)
    c_i_4_2_amount = models.IntegerField(default=0)
    c_i_4_2_note = models.CharField(blank=True, max_length=225)
    # II.Tiếp nhận, giải quyết TTHC tại Bộ phận tiếp nhận và trả kết quả cấp xã
    c_ii_1_amount = models.IntegerField(default=0)
    c_ii_1_note = models.CharField(blank=True, max_length=225)
    c_ii_2_note = models.CharField(blank=True, max_length=225)
    c_ii_2_1_amount = models.IntegerField(default=0)
    c_ii_2_1_note = models.CharField(blank=True, max_length=225)
    c_ii_2_2_amount = models.IntegerField(default=0)
    c_ii_2_2_note = models.CharField(blank=True, max_length=225)
    c_ii_2_3_amount = models.IntegerField(default=0)
    c_ii_2_3_note = models.CharField(blank=True, max_length=225)
    # III.Các nội dung khác
    c_iii_1_amount = models.IntegerField(default=0)
    c_iii_1_note = models.CharField(blank=True, max_length=225)
    c_iii_2_amount = models.IntegerField(default=0)
    c_iii_2_note = models.CharField(blank=True, max_length=225)
    c_iii_3_amount = models.IntegerField(default=0)
    c_iii_3_note = models.CharField(blank=True, max_length=225)
    c_iii_4_amount = models.IntegerField(default=0)
    c_iii_4_note = models.CharField(blank=True, max_length=225)
    c_iii_5_amount = models.IntegerField(default=0)
    c_iii_5_note = models.CharField(blank=True, max_length=225)
    # D.PHÒNG KIỂM TRA GIÁM SÁT
    # I.Tình hình chấp hành kỷ luật kỷ cương hành chính, văn hóa văn minh công sở của cán bộ làm việc tại Trung tâm PVHCC tỉnh trong ngày làm việc
    d_i_1_amount = models.IntegerField(default=0)
    d_i_1_note = models.CharField(blank=True, max_length=225)
    d_i_2_amount = models.IntegerField(default=0)
    d_i_2_note = models.CharField(blank=True, max_length=225)
    d_i_3_amount = models.IntegerField(default=0)
    d_i_3_note = models.CharField(blank=True, max_length=225)
    d_i_4_amount = models.IntegerField(default=0)
    d_i_4_note = models.CharField(blank=True, max_length=225)
    d_i_5_amount = models.IntegerField(default=0)
    d_i_5_note = models.CharField(blank=True, max_length=225)
    d_i_6_amount = models.IntegerField(default=0)
    d_i_6_note = models.CharField(blank=True, max_length=225)
    # II. Khảo sát, đánh giá sự hài lòng của tổ chức, công dân
    d_ii_1_note = models.CharField(blank=True, max_length=225)
    d_ii_1_1_amount = models.IntegerField(default=0)
    d_ii_1_1_note = models.CharField(blank=True, max_length=225)
    d_ii_1_2_amount = models.IntegerField(default=0)
    d_ii_1_2_note = models.CharField(blank=True, max_length=225)
    d_ii_1_3_amount = models.IntegerField(default=0)
    d_ii_1_3_note = models.CharField(blank=True, max_length=225)
    d_ii_1_4_amount = models.IntegerField(default=0)
    d_ii_1_4_note = models.CharField(blank=True, max_length=225)
    d_ii_1_5_amount = models.IntegerField(default=0)
    d_ii_1_5_note = models.CharField(blank=True, max_length=225)
    d_ii_1_6_amount = models.IntegerField(default=0)
    d_ii_1_6_note = models.CharField(blank=True, max_length=225)
    d_ii_1_7_amount = models.IntegerField(default=0)
    d_ii_1_7_note = models.CharField(blank=True, max_length=225)
    # III. Tiếp nhận, xử lý các phản ánh, kiến nghị, khiếu nại, tố cáo của tổ chức, công dân
    d_iii_1_a_note = models.CharField(blank=True, max_length=225)
    d_iii_1_1_amount = models.IntegerField(default=0)
    d_iii_1_1_note = models.CharField(blank=True, max_length=225)
    d_iii_1_2_amount = models.IntegerField(default=0)
    d_iii_1_2_note = models.CharField(blank=True, max_length=225)
    d_iii_1_3_amount = models.IntegerField(default=0)
    d_iii_1_3_note = models.CharField(blank=True, max_length=225)
    d_iii_1_4_amount = models.IntegerField(default=0)
    d_iii_1_4_note = models.CharField(blank=True, max_length=225)
    d_iii_1_b_note = models.CharField(blank=True, max_length=225)
    d_iii_1_5_amount = models.IntegerField(default=0)
    d_iii_1_5_note = models.CharField(blank=True, max_length=225)
    d_iii_1_6_amount = models.IntegerField(default=0)
    d_iii_1_6_note = models.CharField(blank=True, max_length=225)
    d_iii_1_7_amount = models.IntegerField(default=0)
    d_iii_1_7_note = models.CharField(blank=True, max_length=225)
    d_iii_1_8_amount = models.IntegerField(default=0)
    d_iii_1_8_note = models.CharField(blank=True, max_length=225)
    d_iii_2_a_note = models.CharField(blank=True, max_length=225)
    d_iii_2_1_amount = models.IntegerField(default=0)
    d_iii_2_1_note = models.CharField(blank=True, max_length=225)
    d_iii_2_2_amount = models.IntegerField(default=0)
    d_iii_2_2_note = models.CharField(blank=True, max_length=225)
    d_iii_2_3_amount = models.IntegerField(default=0)
    d_iii_2_3_note = models.CharField(blank=True, max_length=225)
    d_iii_2_b_note = models.CharField(blank=True, max_length=225)
    d_iii_2_4_amount = models.IntegerField(default=0)
    d_iii_2_4_note = models.CharField(blank=True, max_length=225)
    d_iii_2_5_amount = models.IntegerField(default=0)
    d_iii_2_5_note = models.CharField(blank=True, max_length=225)
    d_iii_2_6_amount = models.IntegerField(default=0)
    d_iii_2_6_note = models.CharField(blank=True, max_length=225)

    class Meta:
        db_table = 'statistical_information'
