# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-18 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticaldatareport',
            old_name='crate_at',
            new_name='crated_at',
        ),
    ]
