# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190118_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatareport',
            name='a_i_2_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
