# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_statisticaldatareport_a_i_2_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatareport',
            name='a_i_2_4_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statisticaldatareport',
            name='a_i_2_4_note',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
