# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190124_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatareport',
            name='a_ii_2_note',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
