# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_statisticaldatareport_a_ii_2_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatareport',
            name='a_iii_2',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='statisticaldatareport',
            name='a_iii_1_2_note',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
