# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190124_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticaldatareport',
            old_name='a_iii_2',
            new_name='a_iii_2_note',
        ),
    ]
