# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_statisticaldatareport_b_i_2_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatareport',
            name='b_i_3_note',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
