# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_statisticaldatareport_b_i_3_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatareport',
            name='b_ii_2_2_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statisticaldatareport',
            name='b_ii_2_2_note',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
