# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20190124_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatareport',
            name='c_i_3_2_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statisticaldatareport',
            name='c_i_3_2_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='statisticaldatareport',
            name='c_i_4_2_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statisticaldatareport',
            name='c_i_4_2_note',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
