# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20190201_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticaldatareport',
            old_name='d_iii_1_a',
            new_name='d_iii_1_a_note',
        ),
        migrations.AddField(
            model_name='statisticaldatareport',
            name='d_iii_2_a_note',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='statisticaldatareport',
            name='d_iii_2_b_note',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
