# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-11 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20190209_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticaldatareport',
            name='c_ii_2_note',
        ),
    ]
