# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-11 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_statisticaldatareport_c_ii_2_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticaldatareport',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='statisticaldatareport',
            name='name',
        ),
    ]
