# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-12 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20190211_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticaldatareport',
            name='is_looked_for',
        ),
    ]
